-- Professional Snowflake Environment Setup Script
-- Uses Role-Based Access Control (RBAC) best practices

-- 1. Infrastructure Setup
USE ROLE ACCOUNTADMIN;

-- Create Warehouse for Data Engineering (Isolated Compute)
CREATE OR REPLACE WAREHOUSE DE_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Data Engineering and dbt workloads';

-- Create Database and Schemas
CREATE OR REPLACE DATABASE ANALYTICS;
CREATE OR REPLACE SCHEMA ANALYTICS.MARTS_MARKETING;
CREATE OR REPLACE SCHEMA ANALYTICS.STAGING_MARKETING;

-- 2. RBAC Setup
-- Create Custom Roles
CREATE OR REPLACE ROLE DE_ROLE;
CREATE OR REPLACE ROLE ANALYST_ROLE;

-- Hierarchy: SYSADMIN inherits DE_ROLE and ANALYST_ROLE
GRANT ROLE DE_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;

-- 3. Permissions Assignment
-- DE_ROLE Permissions (Full access to Analytics DB)
GRANT USAGE ON WAREHOUSE DE_WH TO ROLE DE_ROLE;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE DE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE DE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE DE_ROLE;

-- ANALYST_ROLE Permissions (Read-only access to Marts)
GRANT USAGE ON WAREHOUSE DE_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS_MARKETING TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS.MARTS_MARKETING TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.MARTS_MARKETING TO ROLE ANALYST_ROLE;

-- 4. User Assignment (Example)
-- GRANT ROLE DE_ROLE TO USER SOME_DATA_ENGINEER;

-- 5. Cleanup / Sanity Check
USE ROLE DE_ROLE;
USE WAREHOUSE DE_WH;
USE DATABASE ANALYTICS;
SELECT 'Snowflake environment initialized successfully.' AS status;
